#!/bin/bash

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7

# This folder contains GROMACS formatted force fields, a pre-optimized PDB structure, and GROMACS inputs.
# All input files were optimized for GROMACS 2019.2 or above, so lower version of GROMACS can cause some errors.
# We adopted the Verlet cut-off scheme for all minimization, equilibration, and production steps because it is 
# faster and more accurate than the group scheme. If you have a trouble with a performance of Verlet scheme while 
# running parallelized simulation, you should check if you are using appropriate command line.
# For MPI parallelizing, we recommend the following command:
# mpirun -np $NUM_CPU gmx mdrun -ntomp 1

init="step5_input"
rest_prefix="step5_input"
mini_prefix="step6.0_minimization"
equi_prefix="step6.%d_equilibration"
prod_prefix="step7_production"
prod_step="step7"

# Function to check if a file exists
check_file_exists() {
    if [ ! -f "$1" ]; then
        echo "Error: File '$1' does not exist or is not accessible."
        exit 1
    fi
}

# Minimization
check_file_exists "${mini_prefix}.mdp"
check_file_exists "${init}.gro"
check_file_exists "${rest_prefix}.gro"
check_file_exists "topol.top"
check_file_exists "index.ndx"

gmx grompp -f ${mini_prefix}.mdp -o ${mini_prefix}.tpr -c ${init}.gro -r ${rest_prefix}.gro -p topol.top -n index.ndx
gmx mdrun -v -deffnm ${mini_prefix}

# Equilibration
cnt=1
cntmax=6

while [ ${cnt} -le ${cntmax} ]
do
    pcnt=$((cnt - 1))
    istep=$(printf ${equi_prefix} ${cnt})
    pstep=$(printf ${equi_prefix} ${pcnt})
    if [ ${cnt} -eq 1 ]; then
        pstep=${mini_prefix}
    fi

    check_file_exists "${istep}.mdp"
    check_file_exists "${pstep}.gro"
    check_file_exists "${rest_prefix}.gro"
    check_file_exists "topol.top"
    check_file_exists "index.ndx"

    gmx grompp -f ${istep}.mdp -o ${istep}.tpr -c ${pstep}.gro -r ${rest_prefix}.gro -p topol.top -n index.ndx -maxwarn 1
    gmx mdrun -v -deffnm ${istep}
    cnt=$((cnt + 1))
done

# Production
prod_mdp="step7_production.mdp"
final_equi_gro="step6.6_equilibration.gro"

check_file_exists "${prod_mdp}"
check_file_exists "${final_equi_gro}"
check_file_exists "${rest_prefix}.gro"
check_file_exists "topol.top"
check_file_exists "index.ndx"

gmx grompp -f ${prod_mdp} -o ${prod_prefix}.tpr -c ${final_equi_gro} -r ${rest_prefix}.gro -p topol.top -n index.ndx -maxwarn 1
gmx mdrun -v -deffnm ${prod_prefix}
